### PR TITLE
add powered by logos

### PR DESCRIPTION
**Pull request by tobowers**
Screen Shot 2021-07-17 at 22 54 17

adds 6 powered by logos

### CODE REVIEW

**Review by alabobriggs — APPROVED** [review]
This is nicee

**Review by alabobriggs — APPROVED** [review]
Looks good, one comment. Let's link the logos to the respective pages

**Comment by tobowers** [comment]
I linked ours - the others are just a bit of work to do - we'll get to it :)

**Comment by alabobriggs** [comment]
> I linked ours - the others are just a bit of work to do - we'll get to it :)

Alright

**Pull request merged**
